#!/bin/bash
#
#SBATCH --mail-user=chaofeng@cs.uchicago.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/home/chaofeng/slurm/out/%j.%N.stdout
#SBATCH --error=/home/chaofeng/slurm/out/%j.%N.stderr
#SBATCH --workdir=/home/chaofeng/slurm
#SBATCH --partition=general
#SBATCH --job-name=chaofeng_test
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=2000
#SBATCH --time=1-06:00

cd /scratch/chaofeng/TTIC31230/
bash run.sh
